### ISSUE TITLE
'Copy all links' Red Button MISSING!

### ISSUE THREAD

**Issue by amirmohideenaus** [datazinc/easy-tiktok-video-downloader#3]
Hi,

The 'Copy all links' Red Button is no longer being shown when using the extension.
Due to this, I am unable to copy all the videos download links at once and use it to bulk download as usual.

Kindly check this issue and please resolve this.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/70577632/179245375-c583aa29-5ab1-4f71-9c83-f6a9b73b140f.png">

**Comment by aimuhire** [comment]
Hello, @amirmohideen  this is a known issue. Could you try to log into your TikTok before using the extension? This seems to fix the problem on my end.

**Comment by aimuhire** [comment]
I will look into fixing this ASAP

**Comment by amirmohideenaus** [comment]
Hi,

Thanks for the quick response. After logging in, it works. Thank you!
