### ISSUE TITLE
Unable to download any videos due to HTTP Error 403 'Restricted Access'

### ISSUE THREAD

**Issue by amirmohideenaus** [datazinc/easy-tiktok-video-downloader#4]
Hi,

I use Free Download Manager to download videos from the links your extension provides. 
However, recently they dont download since it gives me a HTTP Error 403.

When I tried searching up each video's individual download link given by extension, it gave me this error:
> Access Denied
> You don't have permission to access "link from extension" on this server.
> Reference #18.19120217.167701

<img width="476" alt="Access Denied" src="https://user-images.githubusercontent.com/70577632/220463976-fbb45ab3-55e9-4408-9eab-1c997515a2cf.png">

Maybe TikTok patched it? Could you troubleshoot from your end?

**Comment by aimuhire** [comment]
This error is related to new API changes by TikTok. The only way to get around it is to have cookies in your downloader.
https://www.google.com/search?q=use+cookies+wget&oq=use+cookies+wget
